---
apiVersion: ako.vmware.com/v1alpha1
kind: HostRule
metadata:
  name: my-host-rule
spec:
  virtualhost:
    fqdn: empower22.tkgsingress.livefire.lab # mandatory
    enableVirtualHost: true
    gslb:
      fqdn: vip1.global.avi.com
    wafPolicy: System-WAF-Policy-empower22
    tls:
      sslKeyCertificate:
        name: empowertls
        type: ref
      sslProfile: System-Standard
      termination: edge
    analyticsPolicy: # optional
      fullClientLogs:
        enabled: true
        throttle: HIGH
      logAllHeaders: true